/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments.js";
import * as core from "../../../../core/index.js";
import * as BrowsernessApi from "../../../index.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as errors from "../../../../errors/index.js";

export declare namespace Browsers {
    export interface Options {
        environment?: core.Supplier<environments.BrowsernessApiEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token?: core.Supplier<core.BearerToken | undefined>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
}

/**
 * Operations related to browser instance management
 */
export class Browsers {
    protected readonly _options: Browsers.Options;

    constructor(_options: Browsers.Options = {}) {
        this._options = _options;
    }

    /**
     * List all browser instances from database (single source of truth).
     *
     * @param {Browsers.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.browsers.listBrowsers()
     */
    public listBrowsers(
        requestOptions?: Browsers.RequestOptions,
    ): core.HttpResponsePromise<BrowsernessApi.BrowserListResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listBrowsers(requestOptions));
    }

    private async __listBrowsers(
        requestOptions?: Browsers.RequestOptions,
    ): Promise<core.WithRawResponse<BrowsernessApi.BrowserListResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrowsernessApiEnvironment.Default,
                "browsers",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as BrowsernessApi.BrowserListResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.BrowsernessApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.BrowsernessApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.BrowsernessApiTimeoutError("Timeout exceeded when calling GET /browsers.");
            case "unknown":
                throw new errors.BrowsernessApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Create a new browser instance.
     *
     * @param {BrowsernessApi.BrowserCreateRequest} request
     * @param {Browsers.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrowsernessApi.UnprocessableEntityError}
     *
     * @example
     *     await client.browsers.createBrowser()
     */
    public createBrowser(
        request: BrowsernessApi.BrowserCreateRequest = {},
        requestOptions?: Browsers.RequestOptions,
    ): core.HttpResponsePromise<BrowsernessApi.BrowserResponseModel> {
        return core.HttpResponsePromise.fromPromise(this.__createBrowser(request, requestOptions));
    }

    private async __createBrowser(
        request: BrowsernessApi.BrowserCreateRequest = {},
        requestOptions?: Browsers.RequestOptions,
    ): Promise<core.WithRawResponse<BrowsernessApi.BrowserResponseModel>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrowsernessApiEnvironment.Default,
                "browsers",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as BrowsernessApi.BrowserResponseModel, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new BrowsernessApi.UnprocessableEntityError(
                        _response.error.body as BrowsernessApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.BrowsernessApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.BrowsernessApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.BrowsernessApiTimeoutError("Timeout exceeded when calling POST /browsers.");
            case "unknown":
                throw new errors.BrowsernessApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get a specific browser instance from database.
     *
     * @param {string} browserId
     * @param {Browsers.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrowsernessApi.UnprocessableEntityError}
     *
     * @example
     *     await client.browsers.getBrowser("browser_id")
     */
    public getBrowser(
        browserId: string,
        requestOptions?: Browsers.RequestOptions,
    ): core.HttpResponsePromise<BrowsernessApi.BrowserResponseModel> {
        return core.HttpResponsePromise.fromPromise(this.__getBrowser(browserId, requestOptions));
    }

    private async __getBrowser(
        browserId: string,
        requestOptions?: Browsers.RequestOptions,
    ): Promise<core.WithRawResponse<BrowsernessApi.BrowserResponseModel>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrowsernessApiEnvironment.Default,
                `browsers/${encodeURIComponent(browserId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as BrowsernessApi.BrowserResponseModel, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new BrowsernessApi.UnprocessableEntityError(
                        _response.error.body as BrowsernessApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.BrowsernessApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.BrowsernessApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.BrowsernessApiTimeoutError(
                    "Timeout exceeded when calling GET /browsers/{browser_id}.",
                );
            case "unknown":
                throw new errors.BrowsernessApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Delete a browser instance.
     *
     * @param {string} browserId
     * @param {Browsers.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrowsernessApi.UnprocessableEntityError}
     *
     * @example
     *     await client.browsers.deleteBrowser("browser_id")
     */
    public deleteBrowser(
        browserId: string,
        requestOptions?: Browsers.RequestOptions,
    ): core.HttpResponsePromise<BrowsernessApi.DeleteResponse> {
        return core.HttpResponsePromise.fromPromise(this.__deleteBrowser(browserId, requestOptions));
    }

    private async __deleteBrowser(
        browserId: string,
        requestOptions?: Browsers.RequestOptions,
    ): Promise<core.WithRawResponse<BrowsernessApi.DeleteResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrowsernessApiEnvironment.Default,
                `browsers/${encodeURIComponent(browserId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as BrowsernessApi.DeleteResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new BrowsernessApi.UnprocessableEntityError(
                        _response.error.body as BrowsernessApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.BrowsernessApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.BrowsernessApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.BrowsernessApiTimeoutError(
                    "Timeout exceeded when calling DELETE /browsers/{browser_id}.",
                );
            case "unknown":
                throw new errors.BrowsernessApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string | undefined> {
        const bearer = await core.Supplier.get(this._options.token);
        if (bearer != null) {
            return `Bearer ${bearer}`;
        }

        return undefined;
    }
}
