/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         name: "name",
 *         user_id: "user_id"
 *     }
 */
export interface CreateTokenRequestEnhanced {
    "X-Admin-Key"?: string;
    name: string;
    user_id: string;
    scopes?: string[];
    expires_in_days?: number;
    revoke_existing?: boolean;
    store_raw_token?: boolean;
}
