/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class BrowsernessApiTimeoutError extends Error {
    constructor(message: string) {
        super(message);
        Object.setPrototypeOf(this, BrowsernessApiTimeoutError.prototype);
    }
}
