/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BrowsernessApi from "../index.js";

/**
 * Response for listing browsers (simple API).
 */
export interface BrowserListResponse {
    browsers: BrowsernessApi.BrowserResponseModel[];
    total: number;
}
