/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Browser response for simple API.
 */
export interface BrowserResponseModel {
    id: string;
    status: string;
    cdp_url?: string;
    wss_url?: string;
    created_at: string;
    region?: string;
    timeout?: number;
    expiration_time?: string;
}
