/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Health check response.
 */
export interface HealthCheckResponse {
    is_healthy: boolean;
    status: string;
    details: Record<string, any>;
    checked_at: string;
}
