/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BrowsernessApi from "../index.js";

export interface HttpValidationError {
    detail?: BrowsernessApi.ValidationError[];
}
