/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments.js";
import * as core from "./core/index.js";
import { mergeHeaders } from "./core/headers.js";
import { Health } from "./api/resources/health/client/Client.js";
import { Browsers } from "./api/resources/browsers/client/Client.js";
import { Resources } from "./api/resources/resources/client/Client.js";
import { Tokens } from "./api/resources/tokens/client/Client.js";

export declare namespace BrowsernessApiClient {
    export interface Options {
        environment?: core.Supplier<environments.BrowsernessApiEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token?: core.Supplier<core.BearerToken | undefined>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
}

export class BrowsernessApiClient {
    protected readonly _options: BrowsernessApiClient.Options;
    protected _health: Health | undefined;
    protected _browsers: Browsers | undefined;
    protected _resources: Resources | undefined;
    protected _tokens: Tokens | undefined;

    constructor(_options: BrowsernessApiClient.Options = {}) {
        this._options = {
            ..._options,
            headers: mergeHeaders(
                {
                    "X-Fern-Language": "JavaScript",
                    "X-Fern-Runtime": core.RUNTIME.type,
                    "X-Fern-Runtime-Version": core.RUNTIME.version,
                },
                _options?.headers,
            ),
        };
    }

    public get health(): Health {
        return (this._health ??= new Health(this._options));
    }

    public get browsers(): Browsers {
        return (this._browsers ??= new Browsers(this._options));
    }

    public get resources(): Resources {
        return (this._resources ??= new Resources(this._options));
    }

    public get tokens(): Tokens {
        return (this._tokens ??= new Tokens(this._options));
    }
}
