/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const BrowsernessApiEnvironment = {
    Default: "https://api.browserness.com",
} as const;

export type BrowsernessApiEnvironment = typeof BrowsernessApiEnvironment.Default;
