/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface BrowserCreateRequest {
    /** Optional proxy server */
    proxy_server?: string;
    /** Whether to run browser in headless mode */
    headless?: boolean;
    /** Preferred region for the browser */
    region?: string;
}
